---
services:
  sut:
    build: ./tests/resources/sut
    command: pytest -v /home/flytekit/tests
    container_name: sut
    environment:
      - FLYTE_KIT_VERSION=${FLYTE_KIT_VERSION}
    volumes:
      - "./tests:/home/flytekit/tests"
