---
version: "3"

services:
  example-spark:
    command: ["run", "fspark.py", "my_spark"]
    entrypoint: pyflyte
    image: ghcr.io/cbdq-io/flyte:latest
    volumes:
      - ".:/example"
    working_dir: /example
