---
services:
  example-wine:
    build: .
    command: ["pyflyte", "run", "example.py", "training_workflow", "--hyperparameters", "{\"C\":0.1}"]
    image: flyte:latest
    volumes:
      - ".:/example"
    working_dir: /example
