---
services:
  example-wine:
    command: ["pyflyte", "run", "example.py", "training_workflow", "--hyperparameters", "{\"C\":0.1}"]
    environment:
      _PIP_ADDITIONAL_REQUIREMENTS: pyarrow,scikit-learn
    image: flyte:latest
    volumes:
      - ".:/example"
    working_dir: /example
