---
name: CD

on:
  workflow_run:
    workflows:
      - CI
      - Trivy
    types:
      - completed

env:
  REGISTRY: ghcr.io

jobs:
  CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Log in to the Container Registry
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Latest Image
        if: github.ref == 'refs/heads/develop'
        run: make multi-build-latest

      - name: Push Tagged and Latest Image
        if: github.ref == 'refs/heads/main'
        run: make multi-build-tagged

      - name: Create Tag
        if: github.ref == 'refs/heads/main'
        run: make tag
