---
name: CI/CD

on:
  push:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 0 * * TUE'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows this workflow to be called from other workflows
  workflow_call:

env:
  REGISTRY: ghcr.io

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Lint
        run: make lint

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Scan Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "flyte:latest"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Log in to the Container Registry
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Latest Image
        if: github.ref == 'refs/heads/develop'
        run: make multi-build-latest

      - name: Push Tagged and Latest Image
        if: github.ref == 'refs/heads/main'
        run: make multi-build-tagged

      - name: Create Tag
        if: github.ref == 'refs/heads/main'
        run: make tag
