---
name: CI

on:
  push:
    branches-ignore:
      - main

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 0 * * TUE'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Lint
        run: make lint

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Scan Image
        uses: anchore/scan-action@v3
        with:
            by-cve: true
            fail-build: true
            image: "flyte:latest"
            only-fixed: true
            output-format: table
