---
#############################################################################
# GitHub workflow file for the project.
#############################################################################
name: Pipeline

on:
  push:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 0 * * TUE'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows this workflow to be called from other workflows
  workflow_call:

env:
  REGISTRY: ghcr.io

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: make lint

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Smoke Test - ML
        run: docker compose -f examples/wine/docker-compose.yml up

      - name: Smoke Test - Spark
        run: docker compose -f examples/spark/docker-compose.yml up

  Trivy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make build

      - name: Scan Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "flyte:latest"
          trivy-config: trivy.yaml

  CD:
    needs:
      - CI
      - Trivy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container Registry
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Latest Image
        if: github.ref == 'refs/heads/develop'
        run: make multi-build-latest

      - name: Push Tagged and Latest Image
        if: github.ref == 'refs/heads/main'
        run: make multi-build-tagged

      - name: Create Tag
        if: github.ref == 'refs/heads/main'
        run: make tag
