---
#############################################################################
# GitHub workflow file for the project.
#############################################################################
name: Pipeline

on:
  push:
    branches:
      - '**'  # This means it runs on all branches
    tags-ignore:
      - '**'  # This ensures it does not run on tag pushes

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '15 0 * * TUE'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows this workflow to be called from other workflows
  workflow_call:

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1
  DEVELOP_BRANCH: develop
  ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MAIN_BRANCH: main
  REGISTRY: ghcr.io

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: make lint

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Smoke Test - ML
        run: docker compose -f examples/wine/docker-compose.yml up

  Trivy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make build

      - name: Scan Image
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: "flyte:latest"
          scanners: "vuln"
          trivy-config: trivy.yaml

  CD:
    needs:
      - CI
      - Trivy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        if: github.ref_name == env.MAIN_BRANCH || github.ref_name == env.DEVELOP_BRANCH
        uses: docker/setup-buildx-action@v3

      - name: Set the Docker Tag to Latest
        if: github.ref_name == env.DEVELOP_BRANCH
        id: get-tag-latest
        run: echo "TAG=latest" >> $GITHUB_ENV

      - name: Get the Docker Release Tag
        if: github.ref_name == env.MAIN_BRANCH
        id: get-tag-release
        run: echo "TAG=$(make tag)" >> $GITHUB_ENV

      - name: Get Flyte Kit version
        id: get-flyte-kit-version
        run: echo "FLYTE_KIT_VERSION=$(make flyte-kit-version)" >> $GITHUB_ENV

      - name: Get Python version
        id: get-python-version
        run: echo "FLYTE_PYTHON_VERSION=$(make python-version)" >> $GITHUB_ENV

      - name: Log in to the Container Registry
        if: github.ref_name == env.MAIN_BRANCH || github.ref_name == env.DEVELOP_BRANCH
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Images for Multiple Architectures
        if: github.ref_name == env.MAIN_BRANCH || github.ref_name == env.DEVELOP_BRANCH
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/cbdq-io/flyte:${{ env.TAG }}
          build-args: |
            DOCKER_IMAGE=ghcr.io/cbdq-io/flyte:${{ env.TAG }}
            FLYTE_KIT_VERSION=${{ env.FLYTE_KIT_VERSION }}
            FLYTE_PYTHON_VERSION=${{ env.FLYTE_PYTHON_VERSION }}
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=A Docker Image for Flyte Kit and Spark.
